### ISSUE TITLE
Still active ?

### ISSUE THREAD

**Issue by akuckartz** [OKFNat/offenewahlen-nrw17#234]
The latest changes are three years old and recently lots of issues were closed without any explanation.

Is this project still active? If not: can this please be stated at the top of the README ?

**Comment by skasberger** [comment]
The project is not active anymore, as Open Knowledge Austria does not exist anymore for more than 2 years. Started a new project from scratch 2 weeks ago, you can find here: https://github.com/skasberger/owat_api

**Comment by akuckartz** [comment]
You could add that information here:
https://github.com/OKFNat/offenewahlen_api
